server.port=8081


# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=no-value
spring.datasource.password=no-value
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Weather API
openweathermap.api.key=no-value
