server.port=8081


# PostgreSQL DB config
spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=royj1
spring.datasource.password=secret
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Weather API
openweathermap.api.key=c00c952b5a696a64b710cdaddfedf9e7